#ifndef __RDPARSER_H
#define __RDPARSER_H

int FuncParam();
int FuncParams();
int FuncDef();
int InitVals();
int InitVal();
int VarDef();
int CompUnit();
int VarDecl();
int VarDecls();
int ConstInitvals();
int ConstInitval();
int ConstExps();
int ConstDef();
int ConstDefs();
int ConstDecl();
int Decl();
int BlockItems();
int Block();
int Stmt();
int RelExp();
int EqExp();
int LAndExp();
int LOrExp();
int CallParams();
int ArraySubscripts();
int LVal();
int Exp();
int PrimaryExp();
int UnaryExp();
int MulExp();
int AddExp();
int ConstExp();
int Type();
#endif
